apiVersion: v1
kind: {{ .Values.volume.kind }}
metadata:
  name: {{ .Values.volume.name }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}