CREATE TABLE IF NOT EXISTS orders (
	id UUID PRIMARY KEY,
	amount REAL NOT NULL,
	user_id UUID NOT NULL,
	payee_id UUID NOT NULL,
	description VARCHAR(500) NOT NULL,
	status VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)