autoscaling:
  enabled: false

replicaCount: 1

image: 
  repository: seanwong/eso-pwn.order
  pullPolicy: Always
  tag: latest

ports:
  - containerPort: 3000

configMap:
  metadata:
    name: order-envs
    data:
      - name: DATABASE_URL
        value: postgres://postgres@order-db.default.svc.cluster.local/postgres?sslmode=disable
      - name: GRPC_SERVER_IP
        value: event-store.default.svc.cluster.local
      - name: EVENT_PORT
        value: 50051
      - name: NATS_STREAMING_CLUSTER_ID
        value: dev
      - name: NATS_STREAMING_CLIENT_ID
        value: order
      - name: NATS_STREAMING_SERVER_URL
        value: nats://nats-streaming-clients.default.svc.cluster.local:4222
        
service:
  - protocol: TCP
    port: 3000
    targetPort: 3000