autoscaling:
  enabled: false

replicaCount: 1

image: 
  repository: nats-streaming
  pullPolicy: IfNotPresent
  tag: linux

ports:
  - name: clients
    containerPort: 4222
  - name: monitoring
    containerPort: 8222

args:
  - "--cluster_id=dev"
  - "--store=SQL"
  - "--sql_driver=postgres"
  - "--sql_source=postgres://postgres@nats-streaming-db.default.svc.cluster.local/postgres?sslmode=disable"
  - "--sql_no_caching=true"
  - "--sql_max_open_conns=80"
  - "--http_port=8222"

service:
  monitoring:
    - protocol: TCP
      port: 8222
      targetPort: 8222
  clients:
    - protocol: TCP
      port: 4222
      targetPort: 4222