apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-monitoring
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range .Values.service.monitoring }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}